CREATE TABLE filyal (
  id SERIAL PRIMARY KEY,
  image TEXT,
  address VARCHAR(1000),
  location TEXT NOT NULL,
  longuage TEXT NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  phone VARCHAR(50) NOT NULL,
  creator INTEGER NOT NULL,
  min_time VARCHAR(50) NOT NULL,
  time_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  time_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  phone VARCHAR(50),
  password TEXT NOT NULL,
  username VARCHAR(64) NOT NULL,
  superadmin BOOLEAN DEFAULT FALSE NOT NULL,
  last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  email VARCHAR(255) NOT NULL,
  category INTEGER DEFAULT 0 NOT NULL,
  UNIQUE(email),
  time_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  time_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE verify (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  username VARCHAR(64) NOT NULL,
  password TEXT NOT NULL,
  code VARCHAR(6) NOT NULL,
  time_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  time_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE filyal_mark (
  id SERIAL PRIMARY KEY,
  mark TEXT NOT NULL,
  text VARCHAR(1000) NOT NULL,
  look BOOLEAN DEFAULT FALSE NOT NULL,
  creator VARCHAR(200) NOT NULL,
  filyal_id INTEGER NOT NULL,
  time_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  time_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE zakaz (
  id SERIAL PRIMARY KEY,
  time_end TIME NOT NULL,
  time_start TIME NOT NULL,
  day_zakaz DATE NOT NULL,
  mutahasis_id INTEGER NOT NULL,
  message TEXT NOT NULL,
  user_id INTEGER NOT NULL,
  time_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  time_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE category (
  id SERIAL PRIMARY KEY,
  category VARCHAR(255) NOT NULL,
  time_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  time_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE mutahasis (
  id SERIAL PRIMARY KEY,
  category INTEGER NOT NULL,
  tavsif TEXT,
  description TEXT NOT NULL,
  filial_id INTEGER NOT NULL,
  price INTEGER NOT NULL,
  time_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  time_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE mutahasis_time (
  id SERIAL PRIMARY KEY,
  time TEXT NOT NULL,
  mutahasis_id INTEGER NOT NULL,
  time_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  time_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE mutahasis_image (
  id SERIAL PRIMARY KEY,
  image TEXT NOT NULL,
  mutahasis_id INTEGER NOT NULL,
  time_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  time_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE filyal_image (
  id SERIAL PRIMARY KEY,
  image TEXT NOT NULL,
  filyal_id INTEGER NOT NULL,
  time_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  time_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE xususiyat (
  id SERIAL PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  time_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  time_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE xususiyat_mutahasis (
  id SERIAL PRIMARY KEY,
  xususiyat_id INTEGER NOT NULL,
  mutahasis_id INTEGER NOT NULL,
  time_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  time_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE xususiyat_filyal (
  id SERIAL PRIMARY KEY,
  xususiyat_id INTEGER NOT NULL,
  filyal_id INTEGER NOT NULL,
  time_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  time_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE rayon (
  id SERIAL PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  time_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  time_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE metro (
  id SERIAL PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  time_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  time_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE metro_filyal (
  id SERIAL PRIMARY KEY,
  metro_id INTEGER NOT NULL,
  filyal_id INTEGER NOT NULL,
  time_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  time_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE rayon_filyal (
  id SERIAL PRIMARY KEY,
  rayon_id INTEGER NOT NULL,
  filyal_id INTEGER NOT NULL,
  time_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  time_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE contact (
  id SERIAL PRIMARY KEY,
  nomer INTEGER NOT NULL,
  ism VARCHAR(20) NOT NULL,
  creator INTEGER NOT NULL,
  mutahasis_id INTEGER NOT NULL,
  time_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  time_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);